stages:
  batch_etl_ml:
    cmd: python3 scripts/run_spark_ml_processing.py
    deps:
      - scripts/run_spark_ml_processing.py
      - data/bigdata/earthquake_bigdata.csv

  evaluation:
    cmd: python3 scripts/run_spark_evaluation.py
    deps:
      - scripts/run_spark_evaluation.py
      - data/bigdata/earthquake_bigdata.csv
